/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import apoio.CombosDAO;
import apoio.Formatacao;
import dao.CompraDAO;
import entidade.Compra;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import apoio.ComboItem;
import dao.FornecedorDAO;
import entidade.Fornecedor;
import apoio.Validacao;

/**
 *
 * @author Leonardo Krindges
 */
public class IfrCompra extends javax.swing.JInternalFrame {

    int idCompra = 0;
    /**
     * Creates new form IfrCompra
     */
    public IfrCompra() {
        initComponents();
        new CompraDAO().popularTabela(tblCompra, "");

        Formatacao.formatarData(tffDataCompra);

        new CombosDAO().popularCombo("fornecedor", cmbCompra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jtpManutencaoCompra = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompra = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCompra = new javax.swing.JComboBox<>();
        tffDataCompra = new javax.swing.JFormattedTextField();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfdConsultarCompra = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();

        jtpManutencaoCompra.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jtpManutencaoCompraAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jtpManutencaoCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtpManutencaoCompraMouseClicked(evt);
            }
        });

        tblCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCompra);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jtpManutencaoCompra.addTab("Listagem", jPanel1);

        jLabel1.setText("Data:");

        jLabel2.setText("Fornecedor:");

        cmbCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tffDataCompra.setText("jFormattedTextField1");
        tffDataCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tffDataCompraFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tffDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tffDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jtpManutencaoCompra.addTab("Manutenção", jPanel2);

        jDesktopPane1.setLayer(jtpManutencaoCompra, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpManutencaoCompra)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpManutencaoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnFechar.setText("Fechar");
        btnFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFecharMouseClicked(evt);
            }
        });
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel3.setText("Busca");

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar)
                        .addGap(14, 14, 14)
                        .addComponent(btnFechar)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfdConsultarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisar)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(jLabel3)
                    .addComponent(tfdConsultarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        System.out.println("salvar");
        if (validarCampos()) {
            CompraDAO compraDAO = new CompraDAO();
            Compra compra = new Compra();
            ComboItem ci = (ComboItem) cmbCompra.getSelectedItem();
            compra.setId(idCompra);
            compra.setData(tffDataCompra.getText());

            if (idCompra == 0) { //Representa uma inserção
                if (compraDAO.salvar(compra) == null) {
                    tffDataCompra.setText("");
                    new CombosDAO().popularCombo("fornecedor", cmbCompra);
                    new CompraDAO().popularTabela(tblCompra, "");

                    JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                    tffDataCompra.requestFocus();
                    Border border = BorderFactory.createLineBorder(Color.gray, 1);
                    cmbCompra.setBorder(border);
                    tffDataCompra.setBorder(border);
                } else {
                    JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
                }
            } else {
                if (compraDAO.atualizar(compra) == null) {
                    tffDataCompra.setText("");
                    new CombosDAO().popularCombo("fornecedor", cmbCompra);
                    new CompraDAO().popularTabela(tblCompra, "");

                    JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                    tffDataCompra.requestFocus();
                    new CompraDAO().popularTabela(tblCompra, "");
                    Border border = BorderFactory.createLineBorder(Color.gray, 1);
                    cmbCompra.setBorder(border);
                    tffDataCompra.setBorder(border);

                } else {
                    JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
                }
            }
        }

        idCompra = 0;    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        idCompra = Integer.parseInt(String.valueOf(tblCompra.getValueAt(tblCompra.getSelectedRow(), 0)));

        Compra compra = new CompraDAO().consultarId(idCompra);

        if (compra != null) {
            jtpManutencaoCompra.setSelectedIndex(1);// Muda a aba manutenção
            tffDataCompra.setText(compra.getData());

            ComboItem ci = (ComboItem) cmbCompra.getSelectedItem();
            Fornecedor fornecedor = new FornecedorDAO().consultarId(compra.getFornecedorId());

            ci.setCodigo(compra.getFornecedorId());
            ci.setDescricao(fornecedor.getNome());

            tffDataCompra.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id da compra não encontrada!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new CompraDAO().popularTabela(tblCompra, tfdConsultarCompra.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        idCompra = Integer.parseInt(String.valueOf(tblCompra.getValueAt(tblCompra.getSelectedRow(), 0)));

        Compra compra = new CompraDAO().consultarId(idCompra);

        if (new CompraDAO().excluir(idCompra) == null) {
            JOptionPane.showMessageDialog(this, "Registro excluído com sucesso!");
            new CompraDAO().popularTabela(tblCompra, "");
        } else {
            JOptionPane.showMessageDialog(this, "Problemas ao excluir registro!");
        }

        idCompra = 0;    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jtpManutencaoCompraAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jtpManutencaoCompraAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jtpManutencaoCompraAncestorMoved

    private void jtpManutencaoCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpManutencaoCompraMouseClicked
        new CombosDAO().popularCombo("fornecedor", cmbCompra);
        tffDataCompra.setText("");
    }//GEN-LAST:event_jtpManutencaoCompraMouseClicked

    private void tffDataCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tffDataCompraFocusLost
//        if (jtpManutencaoCompra.getSelectedIndex() == 0) {// Muda a aba manutenção
//            Border border = BorderFactory.createLineBorder(Color.gray, 1);
//            tffDataCompra.setBorder(border);
//            telaEstaFechada = true;
//        } else if (!telaEstaFechada) {
//            tffDataCompra.requestFocus();
//            validarCampos();
//            telaEstaFechada = false;
//        }
    }//GEN-LAST:event_tffDataCompraFocusLost

    private void btnFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFecharMouseClicked
    }//GEN-LAST:event_btnFecharMouseClicked

    private boolean validarCampos() {

        boolean camposPreenchidos = false;
        ComboItem ci = (ComboItem) cmbCompra.getSelectedItem();

        String dataSemFormatacao = Formatacao.removerFormatacao(tffDataCompra.getText());
        String dataSemEspacoBranco = dataSemFormatacao.replaceAll(" ", "");

        while (!camposPreenchidos) {
            if (dataSemEspacoBranco.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha uma data de compra");
                tffDataCompra.requestFocus();
                Border border = BorderFactory.createLineBorder(Color.RED, 2);
                tffDataCompra.setBorder(border);
                camposPreenchidos = false;
                break;
            } else if (!Validacao.validarDataFormatada(tffDataCompra.getText())) {
                JOptionPane.showMessageDialog(this, "Data inválida!");
                tffDataCompra.requestFocus();
                Border border = BorderFactory.createLineBorder(Color.RED, 2);
                tffDataCompra.setBorder(border);
                camposPreenchidos = false;
                break;
            } else {
                Border border = BorderFactory.createLineBorder(Color.green, 2);
                tffDataCompra.setBorder(border);
            }

            if (ci.getCodigo() == 0) {
                JOptionPane.showMessageDialog(this, "Fornecedor deve ser preenchido");
                cmbCompra.requestFocus();
                Border border = BorderFactory.createLineBorder(Color.RED, 2);
                cmbCompra.setBorder(border);
                camposPreenchidos = false;
                break;
            } else {
                Border border = BorderFactory.createLineBorder(Color.green, 2);
                cmbCompra.setBorder(border);
            }

            camposPreenchidos = true;
        }
        return camposPreenchidos;

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCompra;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jtpManutencaoCompra;
    private javax.swing.JTable tblCompra;
    private javax.swing.JTextField tfdConsultarCompra;
    private javax.swing.JFormattedTextField tffDataCompra;
    // End of variables declaration//GEN-END:variables
}
