/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tela;

import apoio.ComboItem;
import apoio.ConexaoBD;
import apoio.Formatacao;
import apoio.PintaCampos;
import apoio.Validacao;
import dao.FornecedorDAO;
import entidade.Fornecedor;
import java.awt.Color;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Leonardo Krindges
 */
public class IfrFornecedor extends javax.swing.JInternalFrame {

    int idFornecedor = 0;

    /**
     * Creates new form IfrFornecedor
     */
    public IfrFornecedor() {
        initComponents();
        new FornecedorDAO().popularTabela(tblFornecedor, "");

        Formatacao.formatarTelefone(tffTelefoneFornecedor);
        Formatacao.formatarCnpj(tffCnpjFornecedor);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jtpManutencaoFornecedor = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedor = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfdNomeFornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfdEmailFornecedor = new javax.swing.JTextField();
        tffTelefoneFornecedor = new javax.swing.JFormattedTextField();
        tffCnpjFornecedor = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfdConsultarFornecedor = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setTitle("Cadastro: Fornecedor");

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jtpManutencaoFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtpManutencaoFornecedorMouseClicked(evt);
            }
        });

        tblFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFornecedor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtpManutencaoFornecedor.addTab("Listagem", jPanel1);

        jLabel1.setText("Nome");

        tfdNomeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdNomeFornecedorActionPerformed(evt);
            }
        });

        jLabel2.setText("Email");

        jLabel3.setText("Telefone");

        jLabel4.setText("CNPJ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(tfdNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfdEmailFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                            .addComponent(tffTelefoneFornecedor)
                            .addComponent(tffCnpjFornecedor))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfdNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfdEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tffTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tffCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jtpManutencaoFornecedor.addTab("Manutenção", jPanel2);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel5.setText("Busca");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdConsultarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar))
                            .addComponent(jtpManutencaoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfdConsultarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jtpManutencaoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(btnSalvar)
                        .addComponent(btnConsultar)
                        .addComponent(btnEditar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfdNomeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdNomeFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdNomeFornecedorActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (validarCampos()) {
            FornecedorDAO fornecedorDAO = new FornecedorDAO();
            Fornecedor fornecedor = new Fornecedor();

            fornecedor.setNome(tfdNomeFornecedor.getText());
            fornecedor.setEmail(tfdEmailFornecedor.getText());
            fornecedor.setTelefone(tffTelefoneFornecedor.getText());
            fornecedor.setCnpj(tffCnpjFornecedor.getText());

            if (idFornecedor == 0) { //Representa uma inserção
                if (fornecedorDAO.salvar(fornecedor) == null) {
                    tfdNomeFornecedor.setText("");
                    tfdEmailFornecedor.setText("");
                    tffTelefoneFornecedor.setText("");
                    tffCnpjFornecedor.setText("");
                    PintaCampos.pintaBordaCampoCinza(null, tfdNomeFornecedor, null);
                    PintaCampos.pintaBordaCampoCinza(null, tfdEmailFornecedor, null);
                    PintaCampos.pintaBordaCampoCinza(tffTelefoneFornecedor, null, null);
                    PintaCampos.pintaBordaCampoCinza(tffCnpjFornecedor, null, null);

                    JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                    tfdNomeFornecedor.requestFocus();
                    new FornecedorDAO().popularTabela(tblFornecedor, "");
                } else {
                    JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
                }
            } else {
                if (fornecedorDAO.atualizar(fornecedor) == null) {
                    tfdNomeFornecedor.setText("");
                    tfdEmailFornecedor.setText("");
                    tffTelefoneFornecedor.setText("");
                    tffCnpjFornecedor.setText("");
                    PintaCampos.pintaBordaCampoCinza(null, tfdNomeFornecedor, null);
                    PintaCampos.pintaBordaCampoCinza(null, tfdEmailFornecedor, null);
                    PintaCampos.pintaBordaCampoCinza(tffTelefoneFornecedor, null, null);
                    PintaCampos.pintaBordaCampoCinza(tffCnpjFornecedor, null, null);

                    JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
                    tfdNomeFornecedor.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
                }
            }
        }

        idFornecedor = 0;

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ArrayList<Fornecedor> cidades = new ArrayList();

        cidades = new FornecedorDAO().consultarTodos();

        for (int i = 0; i < cidades.size(); i++) {
            System.out.println("Id: " + cidades.get(i).getId());
            System.out.println("Nome: " + cidades.get(i).getNome());
            System.out.println("E-mail: " + cidades.get(i).getEmail());
            System.out.println("Telefone: " + cidades.get(i).getTelefone());
            System.out.println("CNPJ: " + cidades.get(i).getCnpj());

            System.out.println("");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        idFornecedor = Integer.parseInt(String.valueOf(tblFornecedor.getValueAt(tblFornecedor.getSelectedRow(), 0)));

        Fornecedor fornecedor = new FornecedorDAO().consultarId(idFornecedor);

        if (fornecedor != null) {
            jtpManutencaoFornecedor.setSelectedIndex(1);// Muda a aba manutenção
            tfdNomeFornecedor.setText(fornecedor.getNome());
            tfdEmailFornecedor.setText(fornecedor.getEmail());
            tffTelefoneFornecedor.setText(fornecedor.getTelefone());
            tffCnpjFornecedor.setText(fornecedor.getCnpj());

            tfdNomeFornecedor.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "Id do fornecedor não encontrado!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new FornecedorDAO().popularTabela(tblFornecedor, tfdConsultarFornecedor.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        idFornecedor = Integer.parseInt(String.valueOf(tblFornecedor.getValueAt(tblFornecedor.getSelectedRow(), 0)));

        Fornecedor fornecedor = new FornecedorDAO().consultarId(idFornecedor);

        if (new FornecedorDAO().excluir(idFornecedor) == null) {
            JOptionPane.showMessageDialog(this, "Registro excluído com sucesso!");
            new FornecedorDAO().popularTabela(tblFornecedor, "");
        } else {
            JOptionPane.showMessageDialog(this, "Problemas ao excluir registro!");
        }

        idFornecedor = 0;

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jtpManutencaoFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpManutencaoFornecedorMouseClicked
        tfdNomeFornecedor.requestFocus();
    }//GEN-LAST:event_jtpManutencaoFornecedorMouseClicked

    private boolean validarCampos() {

        boolean camposPreenchidos = false;

        while (!camposPreenchidos) {
            if (tfdNomeFornecedor.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nome do fornecedor deve ser preenchido!");
                PintaCampos.pintaBordaCampoVermelho(null, tfdNomeFornecedor, null);
                tfdNomeFornecedor.requestFocus();
                camposPreenchidos = false;
                break;
            } else  {
                PintaCampos.pintaBordaCampoVerde(null, tfdNomeFornecedor, null);
            }

            if (tfdEmailFornecedor.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha um e-mail!");
                PintaCampos.pintaBordaCampoVermelho(null, tfdEmailFornecedor, null);
                tfdEmailFornecedor.requestFocus();
                camposPreenchidos = false;
                break;
            } else if (!Validacao.validarEmail(tfdEmailFornecedor)) {
                JOptionPane.showMessageDialog(this, "Email inválido!");
                camposPreenchidos = false;
                break;
            }

            if (!Validacao.verificaCampoFormatado(tffTelefoneFornecedor.getText(), tffTelefoneFornecedor)) {
                JOptionPane.showMessageDialog(this, "Preencha um telefone");
                camposPreenchidos = false;
                break;
            } else if (!Validacao.validarTelefone(tffTelefoneFornecedor)) {
                JOptionPane.showMessageDialog(this, "Telefone inválido!");
                camposPreenchidos = false;
                break;
            }

            if (!Validacao.verificaCampoFormatado(tffCnpjFornecedor.getText(), tffCnpjFornecedor)) {
                JOptionPane.showMessageDialog(this, "Preencha um CNPJ");
                camposPreenchidos = false;
                break;
            } else if (!Validacao.validarCNPJ(tffCnpjFornecedor)) {
                JOptionPane.showMessageDialog(this, "CNPJ inválido!");
                camposPreenchidos = false;
                break;
            }

            camposPreenchidos = true;
        }
        return camposPreenchidos;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jtpManutencaoFornecedor;
    private javax.swing.JTable tblFornecedor;
    private javax.swing.JTextField tfdConsultarFornecedor;
    private javax.swing.JTextField tfdEmailFornecedor;
    private javax.swing.JTextField tfdNomeFornecedor;
    private javax.swing.JFormattedTextField tffCnpjFornecedor;
    private javax.swing.JFormattedTextField tffTelefoneFornecedor;
    // End of variables declaration//GEN-END:variables
}
